name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Graalvm
        uses: rinx/setup-graalvm-ce@v0.0.1
        with:
          graalvm-version: "20.2.0"
          java-version: "java11"
          native-image: "true"
      - name: Build
        run: |
          java -version
          native-image --version
